/*
===============================================================================
Project      : Project Atlas
Module       : Core Banking
File         : 01_dim_branch.sql
Author       : Olatunji Oseni
Created      : 2026-08-07
Database     : Oracle Database 23 Free

Description:
Creates the Branch Dimension table.

Revision History
-------------------------------------------------------------------------------
Version    Date         Author              Description
-------------------------------------------------------------------------------
1.0        2026-08-07   Olatunji Oseni      Initial Version
===============================================================================
*/

CREATE TABLE dim_branch
(
    branch_id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    branch_code            VARCHAR2(10)      NOT NULL,
    sol_id                 VARCHAR2(10)      NOT NULL,
    branch_name            VARCHAR2(100)     NOT NULL,
    short_name             VARCHAR2(30),
    region                 VARCHAR2(50),
    zone                   VARCHAR2(50),
    state                  VARCHAR2(50),
    city                   VARCHAR2(50),
    country                VARCHAR2(50),
    address                VARCHAR2(200),
    branch_type            VARCHAR2(20),
    branch_classification  VARCHAR2(20),
    branch_manager_id      NUMBER,
    parent_branch_id       NUMBER,
    phone_number           VARCHAR2(20),
    email_address          VARCHAR2(100),
    swift_code             VARCHAR2(15),
    sort_code              VARCHAR2(15),
    opened_date            DATE,
    closed_date            DATE,
    branch_status          VARCHAR2(20) DEFAULT 'ACTIVE',
    is_cash_branch         CHAR(1) DEFAULT 'Y',
    is_head_office         CHAR(1) DEFAULT 'N',
    created_date           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date     TIMESTAMP,
    CONSTRAINT pk_dim_branch
        PRIMARY KEY (branch_id),
    CONSTRAINT uk_dim_branch_code
        UNIQUE (branch_code),
    CONSTRAINT uk_dim_branch_sol
        UNIQUE (sol_id),
    CONSTRAINT chk_branch_status
        CHECK
        (
            branch_status IN
            (
                'ACTIVE',
                'INACTIVE',
                'CLOSED',
                'MERGED'
            )
        ),
    CONSTRAINT chk_cash_branch
        CHECK
        (
            is_cash_branch IN ('Y','N')
        ),
    CONSTRAINT chk_head_office
        CHECK
        (
            is_head_office IN ('Y','N')
        )
);
