CREATE TABLE dim_branch
(
    branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    branch_code VARCHAR2(10) NOT NULL,
    branch_name VARCHAR2(100) NOT NULL,
    branch_status VARCHAR2(20) DEFAULT 'ACTIVE',
    CONSTRAINT pk_dim_branch
        PRIMARY KEY (branch_id),
    CONSTRAINT uk_dim_branch_code
        UNIQUE (branch_code),
    CONSTRAINT chk_branch_status
        CHECK (branch_status IN ('ACTIVE','INACTIVE','CLOSED','MERGED'))
);
