CREATE TABLE dim_currency
(
    currency_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    currency_code VARCHAR2(3) NOT NULL,
    currency_name VARCHAR2(50) NOT NULL,
    currency_symbol VARCHAR2(5),
    decimal_places NUMBER DEFAULT 2,
    exchange_rate NUMBER(18,8) DEFAULT 1,
    is_base_currency CHAR(1) DEFAULT 'N',
    currency_status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_date DATE DEFAULT SYSDATE,
    last_modified_date DATE DEFAULT SYSDATE,
    CONSTRAINT pk_dim_currency
        PRIMARY KEY (currency_id),
    CONSTRAINT uk_dim_currency_code
        UNIQUE (currency_code),
    CONSTRAINT chk_base_currency
        CHECK (is_base_currency IN ('Y','N')),
    CONSTRAINT chk_currency_status
        CHECK (currency_status IN ('ACTIVE','INACTIVE'))
);
