CREATE TABLE dim_schm_code
(
    schm_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    schm_code VARCHAR2(10) NOT NULL,
    schm_name VARCHAR2(100) NOT NULL,
    account_type VARCHAR2(5) NOT NULL,
    product_category VARCHAR2(30),
    interest_bearing CHAR(1) DEFAULT 'Y',
    overdraft_allowed CHAR(1) DEFAULT 'N',
    minimum_balance NUMBER(18,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT pk_dim_schm_code
        PRIMARY KEY (schm_id),
    CONSTRAINT uk_dim_schm_code
        UNIQUE (schm_code),
    CONSTRAINT chk_account_type
        CHECK (account_type IN ('SBA','CAA','ODA','LAA','OAB')),
    CONSTRAINT chk_interest
        CHECK (interest_bearing IN ('Y','N')),
    CONSTRAINT chk_overdraft
        CHECK (overdraft_allowed IN ('Y','N')),
    CONSTRAINT chk_status
        CHECK (status IN ('ACTIVE','INACTIVE'))
);
