CREATE TABLE dim_customer
(
    customer_id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_number            VARCHAR2(20)      NOT NULL,
    customer_type              VARCHAR2(20)      NOT NULL,
    customer_segment           VARCHAR2(30)      NOT NULL,
    first_name                 VARCHAR2(100),
    middle_name                VARCHAR2(100),
    last_name                  VARCHAR2(100),
    full_name                  VARCHAR2(250)     NOT NULL,
    company_name               VARCHAR2(250),
    date_of_birth              DATE,
    gender                     CHAR(1),
    mobile_number              VARCHAR2(20),
    alternate_mobile           VARCHAR2(20),
    email_address              VARCHAR2(150),
    address_line1              VARCHAR2(200),
    address_line2              VARCHAR2(200),
    city                       VARCHAR2(100),
    state                      VARCHAR2(100),
    country                    VARCHAR2(100),
    postal_code                VARCHAR2(20),
    bvn                        VARCHAR2(20),
    nin                        VARCHAR2(20),
    tin                        VARCHAR2(30),
    kyc_level                  NUMBER(2),
    risk_rating                VARCHAR2(20),
    customer_risk_score        NUMBER(5,2),
    pep_flag                   CHAR(1) DEFAULT 'N',
    blacklisted_flag           CHAR(1) DEFAULT 'N',
    home_branch_id             NUMBER,
    preferred_currency_id      NUMBER,
    relationship_manager_id    NUMBER,
    customer_since             DATE DEFAULT SYSDATE,
    customer_status            VARCHAR2(20) DEFAULT 'ACTIVE',
    last_transaction_date      DATE,
    last_credit_date           DATE,
    last_debit_date            DATE,
    created_by                 VARCHAR2(50) DEFAULT USER,
    created_date               TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by                VARCHAR2(50),
    last_modified_date         TIMESTAMP,
    CONSTRAINT pk_dim_customer
        PRIMARY KEY (customer_id),
    CONSTRAINT uk_customer_number
        UNIQUE (customer_number),
    CONSTRAINT uk_customer_bvn
        UNIQUE (bvn),
    CONSTRAINT uk_customer_nin
        UNIQUE (nin),
    CONSTRAINT fk_customer_branch
        FOREIGN KEY (home_branch_id)
        REFERENCES dim_branch(branch_id),
    CONSTRAINT fk_customer_currency
        FOREIGN KEY (preferred_currency_id)
        REFERENCES dim_currency(currency_id),
    CONSTRAINT chk_customer_type
        CHECK (customer_type IN
        (
            'INDIVIDUAL',
            'CORPORATE',
            'STAFF'
        )),
    CONSTRAINT chk_customer_segment
        CHECK (customer_segment IN
        (
            'RETAIL',
            'SME',
            'CORPORATE',
            'GOVERNMENT',
            'STAFF',
            'PRIVATE_BANKING'
        )),
    CONSTRAINT chk_customer_status
        CHECK (customer_status IN
        (
            'ACTIVE',
            'INACTIVE',
            'DORMANT',
            'CLOSED'
        )),
    CONSTRAINT chk_gender
        CHECK (gender IN ('M','F')),
    CONSTRAINT chk_pep
        CHECK (pep_flag IN ('Y','N')),
    CONSTRAINT chk_blacklisted
        CHECK (blacklisted_flag IN ('Y','N'))
);
