CREATE TABLE dim_account
(
    account_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_number              VARCHAR2(20)      NOT NULL,
    customer_id                 NUMBER            NOT NULL,
    schm_id                     NUMBER            NOT NULL,
    branch_id                   NUMBER            NOT NULL,
    currency_id                 NUMBER            NOT NULL,
    account_name                VARCHAR2(250)     NOT NULL,
    account_type                VARCHAR2(5)       NOT NULL,
    account_class               VARCHAR2(20)      DEFAULT 'PERSONAL',
    account_status              VARCHAR2(20)      DEFAULT 'ACTIVE',
    account_open_date           DATE              DEFAULT SYSDATE,
    account_close_date          DATE,
    available_balance           NUMBER(18,2)      DEFAULT 0,
    ledger_balance              NUMBER(18,2)      DEFAULT 0,
    uncleared_balance           NUMBER(18,2)      DEFAULT 0,
    hold_amount                 NUMBER(18,2)      DEFAULT 0,
    minimum_balance             NUMBER(18,2)      DEFAULT 0,
    overdraft_limit             NUMBER(18,2)      DEFAULT 0,
    cum_credit_amt              NUMBER(18,2)      DEFAULT 0,
    cum_debit_amt               NUMBER(18,2)      DEFAULT 0,
    interest_rate               NUMBER(5,2),
    interest_start_date         DATE,
    interest_frequency          VARCHAR2(20),
    last_transaction_date       DATE,
    last_credit_date            DATE,
    last_debit_date             DATE,
    account_dormancy_date       DATE,
    created_by                  VARCHAR2(50)      DEFAULT USER,
    created_date                TIMESTAMP         DEFAULT CURRENT_TIMESTAMP,
    modified_by                 VARCHAR2(50),
    last_modified_date          TIMESTAMP,
    CONSTRAINT pk_dim_account
        PRIMARY KEY (account_id),
    CONSTRAINT uk_account_number
        UNIQUE (account_number),
    CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id)
        REFERENCES dim_customer(customer_id),
    CONSTRAINT fk_account_branch
        FOREIGN KEY (branch_id)
        REFERENCES dim_branch(branch_id),
    CONSTRAINT fk_account_currency
        FOREIGN KEY (currency_id)
        REFERENCES dim_currency(currency_id),
    CONSTRAINT fk_account_schm
        FOREIGN KEY (schm_id)
        REFERENCES dim_schm_code(schm_id),
    CONSTRAINT chk_account_type
        CHECK (account_type IN
        (
            'SBA',
            'CAA',
            'ODA',
            'LAA',
            'OAB'
        )),
    CONSTRAINT chk_account_class
        CHECK (account_class IN
        (
            'PERSONAL',
            'BUSINESS',
            'STAFF',
            'GOVERNMENT',
            'INTERNAL'
        )),
    CONSTRAINT chk_account_status
        CHECK (account_status IN
        (
            'ACTIVE',
            'INACTIVE',
            'DORMANT',
            'FROZEN',
            'CLOSED'
        ))
);
