CREATE TABLE fact_transaction
(
    /* =========================================================
       SURROGATE KEY
       ========================================================= */
    transaction_id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    /* =========================================================
       DATE / TIME DIMENSIONS
       ========================================================= */
    date_id                     NUMBER NOT NULL,
    time_id                     NUMBER,
    value_date_id               NUMBER,
    /* =========================================================
       CORE DIMENSIONS
       ========================================================= */
    account_id                  NUMBER NOT NULL,
    customer_id                 NUMBER,
    transaction_branch_id       NUMBER,
    currency_id                 NUMBER,
    /* =========================================================
       TRANSACTION CLASSIFICATION
       These dimensions use business/source codes as PKs
       ========================================================= */
    tran_type_code              VARCHAR2(5),
    tran_sub_type_code          VARCHAR2(2),
    part_tran_type_code         CHAR(1),
    channel_code                VARCHAR(5),
    rate_id                     NUMBER,
    /* =========================================================
       SOURCE TRANSACTION IDENTIFICATION
       One HTD part transaction = one fact row
       ========================================================= */
    source_tran_id              VARCHAR2(50) NOT NULL,
    part_tran_srl_num           NUMBER NOT NULL,
    /* =========================================================
       GL / SOURCE INFORMATION
       ========================================================= */
    gl_sub_head_code            VARCHAR2(20),
    module_id                   VARCHAR2(30),
    bank_id                     VARCHAR2(10),
    /* =========================================================
       TRANSACTION AMOUNTS
       ========================================================= */
    transaction_amount          NUMBER(18,2),
    reference_amount            NUMBER(18,2),
    fx_transaction_amount       NUMBER(18,2),
    exchange_rate               NUMBER(20,8),
    /* =========================================================
       CURRENCY / REFERENCE INFORMATION
       ========================================================= */
    reference_currency_code     VARCHAR2(10),
    reference_number            VARCHAR2(100),
    /* =========================================================
       TRANSACTION DESCRIPTION
       ========================================================= */
    transaction_particular      VARCHAR2(500),
    transaction_particular_2    VARCHAR2(500),
    /* =========================================================
       TRANSACTION USERS
       ========================================================= */
    entry_user_id               VARCHAR2(50),
    posted_user_id              VARCHAR2(50),
    verified_user_id            VARCHAR2(50),
    /* =========================================================
       SOURCE DATES
       ========================================================= */
    transaction_date            DATE,
    entry_date                  DATE,
    posted_date                 DATE,
    verified_date               DATE,
    gl_date                     DATE,
    /* =========================================================
       STATUS
       ========================================================= */
    transaction_status          VARCHAR2(20),
    delete_flag                 CHAR(1),
    /* =========================================================
       AUDIT
       ========================================================= */
    created_date                TIMESTAMP
                                DEFAULT CURRENT_TIMESTAMP,
    /* =========================================================
       PRIMARY KEY
       ========================================================= */
    CONSTRAINT pk_fact_transaction
        PRIMARY KEY (transaction_id),
    /* =========================================================
       SOURCE TRANSACTION UNIQUENESS

       One TRAN_ID can contain multiple part transactions,
       therefore TRAN_ID alone is not sufficient.
       ========================================================= */
    CONSTRAINT uk_fact_transaction_source
        UNIQUE
        (
            source_tran_id,
            part_tran_srl_num
        ),
    /* =========================================================
       DATE FOREIGN KEYS
       ========================================================= */
    CONSTRAINT fk_fact_transaction_date
        FOREIGN KEY (date_id)
        REFERENCES dim_date(date_id),
    CONSTRAINT fk_fact_transaction_time
        FOREIGN KEY (time_id)
        REFERENCES dim_time(time_id),
    CONSTRAINT fk_fact_transaction_value_date
        FOREIGN KEY (value_date_id)
        REFERENCES dim_date(date_id),
    /* =========================================================
       CORE DIMENSION FOREIGN KEYS
       ========================================================= */
    CONSTRAINT fk_fact_transaction_account
        FOREIGN KEY (account_id)
        REFERENCES dim_account(account_id),
    CONSTRAINT fk_fact_transaction_customer
        FOREIGN KEY (customer_id)
        REFERENCES dim_customer(customer_id),
    CONSTRAINT fk_fact_transaction_branch
        FOREIGN KEY (transaction_branch_id)
        REFERENCES dim_branch(branch_id),
    CONSTRAINT fk_fact_transaction_currency
        FOREIGN KEY (currency_id)
        REFERENCES dim_currency(currency_id),
    /* =========================================================
       TRANSACTION CLASSIFICATION FOREIGN KEYS
       ========================================================= */
    CONSTRAINT fk_fact_transaction_type
        FOREIGN KEY (tran_type_code)
        REFERENCES dim_tran_type(tran_type_code),
    CONSTRAINT fk_fact_transaction_sub_type
        FOREIGN KEY (tran_sub_type_code)
        REFERENCES dim_tran_sub_type(tran_sub_type_code),
    CONSTRAINT fk_fact_transaction_part_type
        FOREIGN KEY (part_tran_type_code)
        REFERENCES dim_part_tran_type(part_tran_type_code),
    /* =========================================================
       OTHER DIMENSIONS
       ========================================================= */
    CONSTRAINT fk_fact_transaction_channel
        FOREIGN KEY (channel_code)
        REFERENCES dim_channel(channel_code),
    CONSTRAINT fk_fact_transaction_rate
        FOREIGN KEY (rate_id)
        REFERENCES dim_rate(rate_id),
    /* =========================================================
       DATA QUALITY CHECKS
       ========================================================= */
    CONSTRAINT chk_fact_transaction_delete
        CHECK (delete_flag IN ('Y', 'N'))
);

channel_id

"CHANNEL_CODE
