CREATE TABLE dim_rate
(
    rate_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rate_date_id            NUMBER NOT NULL,
    from_currency_id        NUMBER NOT NULL,
    to_currency_id          NUMBER NOT NULL,
    rate_type               VARCHAR2(20) NOT NULL,
    exchange_rate           NUMBER(20,8) NOT NULL,
    buy_rate                NUMBER(20,8),
    sell_rate               NUMBER(20,8),
    mid_rate                NUMBER(20,8),
    effective_from          TIMESTAMP NOT NULL,
    effective_to            TIMESTAMP,
    rate_status             VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    source_system           VARCHAR2(50),
    created_by              VARCHAR2(50) DEFAULT USER,
    created_date            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by             VARCHAR2(50),
    last_modified_date      TIMESTAMP,
    CONSTRAINT pk_dim_rate
        PRIMARY KEY (rate_id),
    CONSTRAINT fk_rate_date
        FOREIGN KEY (rate_date_id)
        REFERENCES dim_date(date_id),
    CONSTRAINT fk_rate_from_currency
        FOREIGN KEY (from_currency_id)
        REFERENCES dim_currency(currency_id),
    CONSTRAINT fk_rate_to_currency
        FOREIGN KEY (to_currency_id)
        REFERENCES dim_currency(currency_id),
    CONSTRAINT chk_rate_type
        CHECK (rate_type IN
        (
            'BUY',
            'SELL',
            'MID'
        )),
    CONSTRAINT chk_rate_status
        CHECK (rate_status IN
        (
            'ACTIVE',
            'INACTIVE'
        )),

    CONSTRAINT chk_rate_positive
        CHECK (exchange_rate > 0),
    CONSTRAINT chk_rate_currency_pair
        CHECK (from_currency_id <> to_currency_id)
);
