CREATE TABLE dim_account_officer
(
    account_officer_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_officer_code     VARCHAR2(20)  NOT NULL,
    account_officer_name     VARCHAR2(150),
    account_officer_email    VARCHAR2(150),
    account_officer_phone    VARCHAR2(30),
    officer_status           VARCHAR2(20),
    branch_id                NUMBER,
    created_date             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date       TIMESTAMP,
    CONSTRAINT pk_dim_account_officer
        PRIMARY KEY (account_officer_id),
    CONSTRAINT uk_account_officer_code
        UNIQUE (account_officer_code),
    CONSTRAINT fk_ao_branch
        FOREIGN KEY (branch_id)
        REFERENCES dim_branch(branch_id)
);
